Change structure IncludedNoteTests
it-kmitl-2018/group4 pull request #33
Opened 2018-05-02 15:36 UTC by bosstanayot

Change structure  IncludedNoteTests Test

2018-05-03 02:50 UTC, champillon requested changes
ฝากแก้มาด้วยครับ

2018-05-03 02:50 UTC, champillon commented on src/test/java/com/project/group4/models/IncludedNoteTests.java
> +    public void NullTest() {
ชื่อ method ขึ้นต้นด้วยตัวเล็กสิครับ

2018-05-03 02:50 UTC, champillon commented on src/test/java/com/project/group4/models/IncludedNoteTests.java
> +    public void GetterSetterTest() {
ชื่อ method ขึ้นต้นด้วยตัวเล็กสิครับ

2018-05-03 04:45 UTC, bosstanayot commented
แก้แล้วครับ

2018-05-03 16:40 UTC, champillon approved these changes
รู้สึก PR เล็กไปหน่อย

2018-05-07 17:34 UTC, bosstanayot commented
@mahasak

2018-05-08 03:44 UTC, merged

2018-05-13 03:04 UTC, champillon commented
คะแนนครับ 1 คะแนน
5.1 การ design เป็น components เพื่อทำให้คนอื่นทำงานร่วมกันต่อได้ง่าย => 0 คะแนน
5.2 คุณภาพของการตั้งชื่อตัวแปร, ฟังก์ชั่น และความเรียบร้อยของ code => 0.5 คะแนน
5.3 ความยากเชิงเทคนิคที่นำมาประยุกต์ใช้ เช่น แปลง XML Schema เป็น Java code => 0 คะแนน
5.4 รายละเอียดการตั้งชื่อใน PR name และ commit log รวมทั้งรายละเอียดที่บรรยายใน issue ของ PR นั้นๆ => 0.5 คะแนน
5.5 ความสอดคล้องกันกับ PR อื่นๆของทีม ที่ทำงานร่วมกันได้ดี => 0 คะแนน