Add AddressJson and TradeContactJson model and test
it-kmitl-2018/group4 pull request #63
Opened 2018-05-07 21:03 UTC by intersignature

- Add AddressJson to json package
- Add TradeContactJson to json package
- Add AddressJsonTest to json test package
- Add TradeContactTest to json test package

2018-05-08 03:50 UTC, champillon approved these changes

2018-05-08 05:12 UTC, keattiwut requested changes
ไปแก้ Test มาใหม่ครับ 

New Object ด้วย Null แล้ว Assert มันไม่มีประโยชน์นะครับ

2018-05-08 20:12 UTC, intersignature commented
@keattiwut แก้ Test แล้วครับ

2018-05-08 23:46 UTC, keattiwut requested changes
แก้ test อีกทีนะ
mock data ให้เหมือน data ที่จะใช้จริงๆ หน่อย
ที่น้อง mock มาคนอื่นมาดูจะไม่รู้ว่า data ที่น้อง expect เป็นแบบไหน

2018-05-13 08:41 UTC, intersignature commented
@keattiwut แก้ไขเรียบร้อยครับ แล้วก็มีเปลี่ยนแปลงข้อมูล ​​AddressJson ด้วยนะครับ

2018-05-13 15:12 UTC, keattiwut requested changes
ยังไม่ผ่านนะครับ ไปดูที่ผม comment ตาม line นะ

2018-05-13 15:12 UTC, keattiwut commented on src/test/java/com/project/group4/models/json/AddressJsonTest.java
> +        buildingNumber = "TH";
buildingNumber แต่ทำไมเป็น String?

2018-05-13 15:12 UTC, keattiwut commented on src/test/java/com/project/group4/models/json/AddressJsonTest.java
> +        Boolean expectedBool = true;
expected ไปใส่ใน Assert ก็ได้

2018-05-13 15:12 UTC, keattiwut commented on src/test/java/com/project/group4/models/json/AddressJsonTest.java
> +        Boolean actualBool = JsonConverter.crateJsonFile(addressJson, "test");
return เป็น primitive type อยู่แล้ว เอา Object Boolean มารับให้เปลือง memory ทำไมครับ

2018-05-13 15:12 UTC, keattiwut commented on src/test/java/com/project/group4/models/json/TradeContactJsonTest.java
> +    public void setup() {
ขอ data จริงด้วยครับ Mock แบบนี้ มันบาปนะครับ

2018-05-13 15:58 UTC, intersignature commented on src/test/java/com/project/group4/models/json/AddressJsonTest.java
> +        buildingNumber = "TH";
อันนี้ผมพลาดครับ ลืมเปลี่ยนชื่อตัวแปร ขอโทษด้วยครับ

2018-05-13 15:58 UTC, intersignature commented on src/test/java/com/project/group4/models/json/AddressJsonTest.java
> +        Boolean expectedBool = true;
แก้ไขเรียบร้อยครับ

2018-05-13 15:58 UTC, intersignature commented on src/test/java/com/project/group4/models/json/AddressJsonTest.java
> +        Boolean actualBool = JsonConverter.crateJsonFile(addressJson, "test");
แก้ไขเรียบร้อยครับ

2018-05-13 15:58 UTC, intersignature commented on src/test/java/com/project/group4/models/json/TradeContactJsonTest.java
> +    public void setup() {
แก้ไขเรียบร้อยครับ

2018-05-13 16:13 UTC, keattiwut approved these changes

2018-05-14 04:28 UTC, merged

2018-05-20 17:11 UTC, champillon commented
3.25 คะแนน